---
title: "HW 5 Multilevel Models (MLMs) & Generalized Linear Mixed Models (GLMMs): Handwork Exercises"
subtitle: "Advanced Regression (STAT 353-0)"
author: "YOUR NAME"
pagetitle: "HW 4 Handwork YOUR NAME"
date: today

format:
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true
    theme: cosmo

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin
---

::: {.callout-tip icon=false}

## Github Repo Link

To link to your github **repo**sitory, appropriately edit the example link below. Meaning replace `https://your-github-repo-url` with your github repo url. Suggest verifying the link works before submitting.

[https://your-github-repo-url](https://your-github-repo-url)

:::

::: {.callout-important}

**Required** for PhD and MS students in the Department of Statistics and Data Science. 

These exercises are encouraged (but not required) for MS in Applied Statistics and all other students. These students will not be penalized for attempting these question. Nor will they receive extra credit. 

:::

## Handwork

Exercises are from the course textbook *Applied Regression Analysis & Generalized Linear Models, 3rd Edition (FOX)* ---  23.2, 23.4

You can type your answers directly into this document or you can do the work for each exercise on paper, take a picture of your solution, and include the image within this document (work must be legible). 

Alternatively, you can do the Handwork exercises on paper and submit a scanned copy. This document is expected to be well organized and neat (work must be legible).

### 1. Exercise E23.2

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::


### 2. Exercise E23.4

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::
